const NAVIGATOR = {
    WELCOME: 'WELCOME',
    HOME: 'HOME',
    FAVORITES: 'FAVORITES',
    BOOKINGS: 'BOOKINGS',
    PROFILE: 'PROFILE',
    HOMERE: 'PROPIEDADES',
    AGENDARE: 'AGENDARE',
    UPLOADASSET: 'UPLOADASSET',
    REPROFILE: 'REPROFILE',
    SEARCH:'SEARCH'
}

export default {
    NAVIGATOR
}